<br>
 <br>
 <br>
 <br>
 <br>
 <br>
<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">     
    <form name="formUser" action="" method="post" enctype="multipart/form-data">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">ชื่อกิจกรรม :</label>
          <div class="col-sm-10">
            <input class="form-control" id="name" name="name" value="" required="" type="text">
            <div class="invalid-feedback">
              Please fill data.
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">วันที่ :</label>
          <div class="col-sm-10">
            <input class="form-control" id="day" name="day" required="" type="date"min="2018-01-01" max="2019-12-31" require>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">รายละเอียด :</label>
          <div class="col-sm-10">
            <textarea class="form-control" id="detail" name="detail" required="" type="text"></textarea>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm"></label>
          <div class="col-sm-10">
          <div class="custom-file">
          <input type="file" name="photo"  class="custom-file-input"  >
          <label class="custom-file-label" >Choose file</label>
    </div>
        

          </div>
          
        </div>
        <div class="form-group">
        
          <input class="btn btn-sm btn-success" type="submit" value="Add.">
        </div>
      </form>
      </div>
      <div class="col-sm">     
    </div>
 </div>